# Flower test case
initial_mesh_size: 2.

# Uniform refinement
# iterations_number: 7
# refinement_method: "uniform"

# Adaptive refinement
iterations_number: 25
refinement_method: "H10"

bbox:
- [-4.5, 4.5]
- [-4.5, 4.5]
exact_error: true
ref_degree: 2
marking_parameter: 0.3
use_fine_space: false
box_mode: false
finite_element_degree: 1
levelset_degree: 2
boundary_detection_degree: 2
boundary_refinement_type: 'h'
quadrature_degree: null
stabilization_parameter: 1.0
save_output: true